server: irc.libera.chat:+6697
nickname: cloaks
password: cloaks:hunter2
channel: "#libera-cloak"

sasl:
  username: cloaks
  password: hunter3

oper:
  name: cloaks
  file: ~/libera.key
  pass: hunter4
